const details=[
    {
        name:"ashima",
        age:22,
        id:"1"
    },
    {
        name:"annie",
        age:20,
        id:"2"
    },
    {
        name:"muskan",
        age:21,
        id:"3"
    },
    {
        name:"sapna",
        age:24,
        id:"4",
        college:"jammuuniversity",
        percentage:"89%"
    },
    {
        name:"diksha",
        age:22,
        id:"5",
        college:"jammuuniversity",
        percentage:"80%"
    },
    {
        name:"vitasta",
        age:23,
        id:"6",
        college:"lpu",
        percentage:"89%"
    }
]

module.exports=details;